// Central data file for all projects — cards + modal details

export const projectsData = [
  {
    id: 1,
    title: "Distributed Key-Value Store",
    shortDes: "Built from scratch in Go — custom TCP, consistent hashing, replication, WAL, TTL, and token-bucket rate limiting.",
    stack: ["Go", "TCP", "Consistent Hashing", "Docker", "GitHub Actions"],
    stackColors: ["#00ADD8", "#555", "#FF6B35", "#2496ED", "#2088FF"],
    accentColor: "#00ADD8",
    githubLink: "https://github.com/Lenecplusultra",
    demoLink: null,
    category: "Distributed Systems",
    status: "Completed",
    highlights: [
      "Built in-memory KV store from scratch in Go with GET, SET, DEL, TTL expiry over raw TCP — zero framework dependencies",
      "Implemented LRU eviction and append-only log persistence for crash recovery without data loss",
      "Designed primary-replica replication model for fault tolerance under node failures",
      "Applied consistent hashing for distributed sharding across nodes",
      "Built token-bucket rate limiter for high-throughput request control under concurrent load",
      "Benchmarked throughput and latency under concurrent clients; implemented node failure detection and re-entry recovery",
    ],
    details: "This project was built to deeply understand the internals of distributed storage systems like DynamoDB and Redis — without using any existing frameworks. Every component (networking, persistence, replication, rate limiting) was implemented from scratch to force a real understanding of the trade-offs involved.",
  },
  {
    id: 2,
    title: "Event-Driven Order Fulfillment",
    shortDes: "High-throughput multi-service backend with Kafka, Saga orchestration, Kubernetes autoscaling, and OpenTelemetry tracing.",
    stack: ["Python", "FastAPI", "Kafka", "Redis", "Kubernetes", "OpenTelemetry"],
    stackColors: ["#3776AB", "#009688", "#231F20", "#DC382D", "#326CE5", "#f5a623"],
    accentColor: "#009688",
    githubLink: "https://github.com/Lenecplusultra",
    demoLink: null,
    category: "Backend Systems",
    status: "Completed",
    highlights: [
      "Designed async event streaming across full order lifecycle: placed → accepted → paid → dispatched → delivered",
      "Implemented Saga orchestration pattern with hand-coded compensating transactions for distributed failure recovery",
      "Leveraged Kafka's dead-letter queue with custom routing and retry strategy for resilience",
      "Added Redis caching layer to reduce downstream DB pressure on high-read endpoints",
      "Deployed to Kubernetes with horizontal autoscaling configured for traffic spikes",
      "Instrumented full distributed tracing with OpenTelemetry; built per-service dashboards tracking latency percentiles and failure rates",
    ],
    details: "Designed to demonstrate production-grade event-driven architecture patterns. The system handles the complete lifecycle of an order using Kafka as the backbone, with each service owning its domain and communicating only through events — no direct service-to-service calls.",
  },
  {
    id: 3,
    title: "OpsPilot AI",
    shortDes: "MCP-powered engineering assistant that executes operational tasks via natural language with RBAC, approval gates, and audit logging.",
    stack: ["Python", "FastAPI", "LangChain", "OpenAI", "PostgreSQL", "React"],
    stackColors: ["#3776AB", "#009688", "#1C3A5F", "#10A37F", "#336791", "#61DAFB"],
    accentColor: "#10A37F",
    githubLink: "https://github.com/Lenecplusultra",
    demoLink: null,
    category: "AI Systems",
    status: "Completed",
    highlights: [
      "Built MCP server exposing operational tools: order replay, DLQ retry, metrics queries, runbook lookup",
      "Implemented LangChain-based structured workflows for tool orchestration and retrieval across logs, events, and documentation",
      "Enforced RBAC with per-role tool invocation policies — operators vs admins have different action surfaces",
      "Added approval gates for destructive admin actions (retries, DLQ replay, manual overrides)",
      "Full audit logging for all admin actions with immutable append-only records",
      "Built React admin dashboard for monitoring orders, events, and system health in real time",
    ],
    details: "OpsPilot solves a real problem: on-call engineers spend too much time switching between dashboards, runbooks, and CLI tools. This assistant unifies those surfaces into a single natural-language interface, with security guarantees (RBAC + audit log) that make it safe to give to less experienced operators.",
  },
  {
    id: 4,
    title: "ANBELO Retail Intelligence",
    shortDes: "Cloud-native analytics platform on SAGE ERP — multi-store sales, inventory centralization, executive dashboards and alerts.",
    stack: ["Java", "Spring Boot", "PostgreSQL", "React", "Docker", "AWS"],
    stackColors: ["#ED8B00", "#6DB33F", "#336791", "#61DAFB", "#2496ED", "#FF9900"],
    accentColor: "#FF9900",
    githubLink: "https://github.com/Lenecplusultra",
    demoLink: null,
    category: "Cloud Platforms",
    status: "Completed",
    highlights: [
      "Ingests SAGE ERP exports and centralizes data across multiple retail store locations",
      "Delivers executive dashboards with revenue analytics, inventory turnover, and sales trends",
      "Automated inventory alerts triggered when stock levels fall below configurable thresholds",
      "Built server-side caching for expensive analytics queries, reducing DB load under concurrent usage",
      "Periodic frontend refresh logic keeps metrics current without manual reloads",
      "Deployed backend services on AWS with storage and compute optimized for cost and scale",
    ],
    details: "Built for a real retail client operating multiple stores on the SAGE ERP system. The core challenge was bridging SAGE's export format into a queryable analytics layer without disrupting existing operations — done through a custom ingestion pipeline that normalizes and loads data on a scheduled basis.",
  },
  {
    id: 5,
    title: "Cogitons",
    shortDes: "Subject-centered knowledge platform for Cameroonian students — full product-first workflow from requirements through DB design.",
    stack: ["Next.js", "FastAPI", "PostgreSQL", "TypeScript"],
    stackColors: ["#000000", "#009688", "#336791", "#3178C6"],
    accentColor: "#3178C6",
    githubLink: "https://github.com/Lenecplusultra",
    demoLink: null,
    category: "Product Engineering",
    status: "In Progress",
    highlights: [
      "Designed for Cameroonian students and young professionals who lack structured subject-based learning resources",
      "Full product-first workflow: requirements doc, architecture diagram, user flows, and database schema before a line of code",
      "Subject-centered model: content organized around topics, not courses — enabling cross-disciplinary exploration",
      "Next.js frontend with FastAPI backend and PostgreSQL — clean separation of concerns",
      "Documented architecture decisions with trade-off analysis",
      "Demonstrates founder mindset: problem definition, market context, and technical execution",
    ],
    details: "Cogitons is intentionally included not because it's finished, but because it demonstrates something most projects don't: product thinking. The public repo contains the full requirements document, architecture decisions, and database schema — showing the ability to go from problem to design before touching code.",
  },
  {
    id: 6,
    title: "AI-Powered Doc Assistant",
    shortDes: "ChatGPT-style semantic search over 200+ internal docs using GPT-4, LangChain, vector embeddings, and real-time WebSocket streaming.",
    stack: ["React", "FastAPI", "LangChain", "GPT-4", "PostgreSQL"],
    stackColors: ["#61DAFB", "#009688", "#1C3A5F", "#10A37F", "#336791"],
    accentColor: "#61DAFB",
    githubLink: "https://github.com/Lenecplusultra/ai-doc-assistant",
    demoLink: "https://ai-doc-assistant-seven.vercel.app/",
    category: "AI Systems",
    status: "Live",
    highlights: [
      "Semantic search interface over 200+ internal documents using GPT-4 and vector embeddings",
      "Real-time response generation with live ChatGPT-style streaming via WebSockets",
      "LangChain RAG pipeline with document chunking, embedding, and retrieval",
      "FastAPI backend with PostgreSQL for document storage and retrieval metadata",
      "Deployed on Vercel (frontend) + Render (backend) with continuous deployment",
      "React frontend with real-time streaming UI — responses appear token by token",
    ],
    details: "This was the first project that combined RAG architecture with a real UX. The main engineering challenge was making retrieval feel fast — chunking strategy, embedding model choice, and similarity threshold all required tuning to get relevant results without too much noise.",
  },
];
